export const GENERATE_TRANSACTIONS = 'GENERATE_TRANSACTIONS';
export const ADD_NEW_PARAMETER = 'NEW_PARAMETER';
export const GET_MCC_CODES = 'GET_MCC_CODES';
export const GET_CURRENCIES_CODES = 'GET_CURRENCIES';
export const GET_PARAMETER_SETS_NAMES = 'GET_PARAMETER_SETS_NAMES';
export const SELECT_PARAMETER_SET= 'SELECT_PARAMETER_SET';
export const GET_PARAMETER_SET = 'GET_PARAMETER_SET';
export const DELETE_PARAMETERS = 'DELETE_PARAMETERS';
export const UPDATE_PARAMETER='UPDATE_PARAMETER';
export const SAVE_PARAMETER_SETS = 'SAVE_PARAMETER_SETS';
export const DELETE_PARAMETER_SETS = 'DELETE_PARAMETER_SETS';
//cards
export const LOAD_CARDS = 'LOAD_CARDS';
export const GET_CARD = 'GET_CARDS';
export const SAVE_CARD = 'SAVE_CARD';
export const DELETE_CARD = 'DELETE_CARD';
//tariffs
export const LOAD_TARIFFS = 'LOAD_TARIFFS';
export const GET_TARIFF = 'GET_TARIFF';
export const SAVE_TARIFF = 'SAVE_TARIFF';
export const DELETE_TARIFF = 'DELETE_TARIFF';