export const GENERATE_TRANSACTIONS = 'GENERATE_TRANSACTIONS';
export const ADD_NEW_PARAMETER = 'NEW_PARAMETER';
export const GET_MCC_CODES = 'GET_MCC_CODES';
export const UPDATE_PARAMETER='UPDATE_PARAMETER';